### ISSUE TITLE
Make the process of adding user custom views more robust

### ISSUE THREAD

**Issue by esthomw** [Wikia/discreETLy#3]
Currently, a user may inject their custom logic and visualization layer to `extra` module in `blueprints` which makes the dashboard flexible. However, there are some obstacles in doing so:
1. The user needs to define whole logic, with OAuth function.
2. The user needs to inject the whole file into an image
3. Any global changes to logic in `views.py` would also need to be reflected on user side

Possible solutions:
* Inject some logic through configuration files (what about user specific imports? what about logic depending on and utilizing configuration options?)
* Auto-generate logic (blueprints) from a list of html files and related python files.

I would like to discuss it here before going into PR mode.

**Comment by esthomw** [comment]
One more idea came to my mind: what about dashboard admin view and form for inputting python and html code? That would require some persistence of code, though.

**Comment by szczeles** [comment]
We could scan all available blueprints in the app initialization and register them under the path prefix mentioned in blueprint declaration. With this pluggable approach, we can extend the system by any feature with no modification to the base code at all. A blueprints can access the global configuration and service classes easily and can have the local logic included as well.

http://flask.pocoo.org/docs/1.0/blueprints/

But this will require enabling OAuth not on blueprint level, but on whole application level to avoid copying handler across the application.

**Comment by esthomw** [comment]
@szczeles could you expand on that idea a bit more? What is the difference between the solution and current state? It seems we can leave it as is and inject one blueprint `extra.py` with all custom logic.

**Comment by szczeles** [comment]
Scalability is the main advantage here. You can include a number of blueprints and keep the code of each tab separated, then just enable/disable them via the configuration file (or via putting the folder in the right place inside Docker image).

**Comment by esthomw** [comment]
Correct, that's how it works now, despite not having a separate folder (all new blueprints go into templates). If we follow that path it should be an easy change.

**Comment by esthomw** [comment]
We have discussed some issues related to this topic during an internal meeting, here are the action plans:
* any user can add a view through a plugin system, in order to do so a plugin module needs to be provided in a `plugins` folder available (path to be determined). Than specific plugin metada needs to be defined in plugin `__init__` file. The convention is to use one endpoint per plugin.
* some plugins need custom logic for specific use cases. This logic should be ingested as e.g. data provider via proper class name definition in `settings.py`. Providing custom logic requires complying with a specific Abstract Base Class.
@szczeles @jcellary  would you like to add something?

**Comment by esthomw** [comment]
We have done a part of this issue, but there is no real need to implement the other part. If we find enough evidence supporting the whole issue we will reopen it or create a new one, more specific.
